lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v1.1.7@sha256:6d395442d370d16a846c479f50d2b2fb992f5eaddd3dac350ff17a15555b4d40
  debug: false
  localK8sAPIEndpoint:
    enabled: true
  # nodeSelector for the DaemonSet
  # Talos uses empty value: "node-role.kubernetes.io/control-plane": ""
  # Generic k8s (k3s, kubeadm) uses: "node-role.kubernetes.io/control-plane": "true"
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
