piraeusServer:
  image:
    repository: ghcr.io/cozystack/cozystack/piraeus-server
    tag: 1.32.3@sha256:8ab419e453c048f6016ccba14c193003104c8203fd524bbf02af2242f65a1285
# Talos-specific workarounds (disable for generic Linux like Ubuntu/Debian)
talos:
  enabled: true
linstor:
  autoDiskful:
    enabled: true
    minutes: 30
    allowCleanup: true
linstorCSI:
  image:
    repository: ghcr.io/cozystack/cozystack/linstor-csi
    tag: v1.10.5@sha256:57e26cdadd762a620ee9471db9a400d9dee4f4c74bc0d0a86fd001b5e6390682
