piraeusServer:
  image:
    repository: ghcr.io/cozystack/cozystack/piraeus-server
    tag: 1.33.2@sha256:898061dba1f49f0987ab766f5257ed7dc18e1b4fd2778b41d2f7a9b71cf3ed82
# Talos-specific workarounds (disable for generic Linux like Ubuntu/Debian)
talos:
  enabled: true
linstor:
  autoDiskful:
    enabled: true
    minutes: 30
    allowCleanup: true
linstorCSI:
  image:
    repository: ghcr.io/cozystack/cozystack/linstor-csi
    tag: v1.10.5@sha256:9cf8ea2b2e267e28623945d7742981e7789900a72ee1e826b5d904f716914818
