backupController:
  image: "ghcr.io/cozystack/cozystack/backup-controller:v1.2.4@sha256:e1971c8523278f2f81e886fa6eea188f6116c5e0991dd0ebd9481dd3a00837f5"
  replicas: 2
  debug: false
  metrics:
    enabled: true
    bindAddress: ":8443"
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
