backupController:
  image: "ghcr.io/cozystack/cozystack/backup-controller:v1.1.7@sha256:34744b9d0be0b1b7c8bfc2cfd741738068f96b50391fdf016df368a280105d9e"
  replicas: 2
  debug: false
  metrics:
    enabled: true
    bindAddress: ":8443"
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
