kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v1.2.4@sha256:2bdca5ff1b3df91129a1b4a97c2ceac92f806d55d97332f421d56bca314ec2d7
    repository: ghcr.io/cozystack/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  extraArgs:
    - --migrate-image=ghcr.io/cozystack/cozystack/kamaji:v1.2.4@sha256:2bdca5ff1b3df91129a1b4a97c2ceac92f806d55d97332f421d56bca314ec2d7
