kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v1.1.7@sha256:05a7d70fac48813eb1c0e50f701d60c557e71762b37577950fc38eade8b23017
    repository: ghcr.io/cozystack/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  extraArgs:
    - --migrate-image=ghcr.io/cozystack/cozystack/kamaji:v1.1.7@sha256:05a7d70fac48813eb1c0e50f701d60c557e71762b37577950fc38eade8b23017
