backupStrategyController:
  image: "ghcr.io/cozystack/cozystack/backupstrategy-controller:v1.2.4@sha256:b0024f20899e508e5755bb7b3d66bbdaf147c4b4e293f0354d1557cd40bd862e"
  replicas: 2
  debug: false
  metrics:
    enabled: true
    bindAddress: ":8443"
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
