backupStrategyController:
  image: "ghcr.io/cozystack/cozystack/backupstrategy-controller:v1.1.7@sha256:7162e7655b6cd434305ce7dd187a710823a2eaea84319e64d7db58aa76e2073a"
  replicas: 2
  debug: false
  metrics:
    enabled: true
    bindAddress: ":8443"
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
